# Generated by Django 5.2.6 on 2025-09-27 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('head_of_department', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('principal', 'Principal'), ('vice_principal', 'Vice Principal'), ('teacher', 'Teacher'), ('admin_staff', 'Administrative Staff'), ('support_staff', 'Support Staff')], max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True, help_text='Brief biography')),
                ('qualifications', models.TextField(blank=True)),
                ('experience_years', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, upload_to='faculty/')),
                ('subjects_taught', models.CharField(blank=True, help_text='Comma-separated subjects', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculty.department')),
            ],
            options={
                'verbose_name_plural': 'Faculty',
                'ordering': ['position', 'last_name'],
            },
        ),
    ]
