# Generated by Django 4.2.7 on 2025-09-28 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(default='fas fa-images', help_text='Font Awesome icon class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Gallery Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GallerySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos_per_page', models.PositiveIntegerField(default=12)),
                ('albums_per_page', models.PositiveIntegerField(default=9)),
                ('allow_photo_download', models.BooleanField(default=False)),
                ('watermark_enabled', models.BooleanField(default=False)),
                ('watermark_text', models.CharField(default="St. Mary's Nyakhobi School", max_length=100)),
                ('max_photo_size_mb', models.PositiveIntegerField(default=5)),
                ('thumbnail_quality', models.PositiveIntegerField(default=85)),
            ],
            options={
                'verbose_name': 'Gallery Settings',
                'verbose_name_plural': 'Gallery Settings',
            },
        ),
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cover_photo', models.ImageField(blank=True, upload_to='gallery/covers/')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured albums section')),
                ('is_published', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='gallery.gallerycategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('caption', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='gallery/photos/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='gallery/thumbnails/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which photos appear')),
                ('photographer', models.CharField(blank=True, max_length=100)),
                ('taken_date', models.DateTimeField(blank=True, null=True)),
                ('is_cover_photo', models.BooleanField(default=False)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gallery.photoalbum')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='gallery.photo')),
            ],
            options={
                'indexes': [models.Index(fields=['photo', 'ip_address'], name='gallery_pho_photo_i_25064e_idx')],
                'unique_together': {('photo', 'ip_address')},
            },
        ),
        migrations.AddIndex(
            model_name='photoalbum',
            index=models.Index(fields=['slug'], name='gallery_pho_slug_8bc18f_idx'),
        ),
        migrations.AddIndex(
            model_name='photoalbum',
            index=models.Index(fields=['is_published', '-created_at'], name='gallery_pho_is_publ_3ba674_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['album', 'order'], name='gallery_pho_album_i_d6fe65_idx'),
        ),
    ]
