# Generated by Django 5.2.6 on 2025-09-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='slider/')),
                ('link_text', models.CharField(blank=True, max_length=50)),
                ('link_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('icon', models.CharField(help_text='Font Awesome icon class', max_length=50)),
                ('link_url', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default="St. Mary's Nyakhobi Senior School", max_length=200)),
                ('tagline', models.CharField(default='Building Leaders for Tomorrow', help_text='Short description of the school', max_length=300)),
                ('welcome_message', models.TextField(default="St. Mary's Nyakhobi Senior School is a Sub-County public mixed day school committed to academic excellence, discipline and community service.", help_text='Welcome message for homepage')),
                ('mission_statement', models.TextField(default='To provide quality, holistic education that develops academic excellence, discipline, character, and life skills in our students, preparing them to be responsible leaders and productive citizens in their communities and beyond.')),
                ('vision_statement', models.TextField(default='To be a leading educational institution in Busia County that builds leaders for tomorrow through academic excellence, community service, and character development.')),
                ('established_year', models.IntegerField(default=1980)),
                ('phone', models.CharField(default='+254 722 231798 / +254 723 273109', max_length=50)),
                ('email', models.EmailField(default='nyakhobisecondaryschool@gmail.com', max_length=254)),
                ('address', models.TextField(default='Off Nambuku/Funyula Rd, Funyula, P.O. Box 254, Funyula 50406, Busia County, Kenya')),
            ],
            options={
                'verbose_name': 'School Information',
                'verbose_name_plural': 'School Information',
            },
        ),
    ]
