# Generated by Django 4.2.7 on 2025-09-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinfo',
            name='address',
            field=models.TextField(default='P.O. Box 254-50406, Funyula, Nyakhobi Sub-location, Namboboto Location, Samia Sub-County, Busia County, Kenya'),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='email',
            field=models.EmailField(default='nyakhobisecsch@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='established_year',
            field=models.IntegerField(default=1983),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='mission_statement',
            field=models.TextField(default='To consistently and persistently provide quality secondary education.'),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='phone',
            field=models.CharField(default='+254 719 831 346', max_length=50),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='vision_statement',
            field=models.TextField(default='To be an institution of excellence in pursuit of quality and holistic education.'),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='welcome_message',
            field=models.TextField(default="St. Mary's Nyakhobi Senior School (formerly Nyakhobi Secondary School) is located in Nyakhobi Sub-location, Namboboto Location, Samia Sub-County, Busia County, Kenya. The school is sponsored by ACK Church Nambale Diocese and started in 1983 with 6 students.", help_text='Welcome message for homepage'),
        ),
    ]
